### PR TITLE
Add support for DATE-TIME values and email attendees

### PR DESCRIPTION
**Pull request by mkj28**
PagerDuty generates events like this:
BEGIN:VEVENT
DTEND;VALUE=DATE-TIME:20180717T170000Z
DTSTART;VALUE=DATE-TIME:20180710T170000Z
ATTENDEE:test@test.com
UID:Q1234
URL:https://gladly.pagerduty.com/schedules#PPPPPPP
SUMMARY:My summary
END:VEVENT

### CODE REVIEW

**Comment by leosunmo** [comment]
@mkj28 if you don't see any action here I'm considering supporting my fork with a bunch of the PRs awaiting review and merge in this repository. I have already added some functionality to my fork and I'm using it in a project at the moment.

**Comment by mkj28** [comment]
> I'm considering merging a bunch of the PRs awaiting review and merge in this repository to my fork. 

+1 let me know if you want a PR targeting your fork

**Review by PuloV — CHANGES_REQUESTED** [review]
I don't see any changes in tests. 
Please add/extend tests

**Comment by buildscientist** [comment]
@leosunmo @mkj28 The repository is being revived. Do you mind submitting PR's for your changes?

**Comment by mkj28** [comment]
> @leosunmo @mkj28 The repository is being revived. Do you mind submitting PR's for your changes?

I hope to get to it sometimes this week.

**Comment by mkj28** [comment]
@buildscientist  / @leosunmo  / @PuloV rebased latest master, added tests.

**Review by mkj28 — COMMENTED** [review]
tests added now

**Comment by mkj28** [comment]
@PuloV  / @buildscientist  any plans to get this merged?

**Review by PuloV — COMMENTED** [review]
Please check
```
=== Failed
=== FAIL: . TestCalendarMultidayEventWithDurationInsteadOfEndDate (0.00s)
    parse_test.go:642: Expected 1 calendar, found 0 calendars
```

**Comment by mkj28** [comment]
> Please check

will do

**Comment by mkj28** [comment]
> Please check

cannot reproduce - tests passing locally for me, also ran inside circleci docker - also passing, not sure what can be wrong? can we try rerunning the circleci build?

**Pull request merged**
